medianet-distribution-website/Medianet.Web/Controllers/TrainingCourseController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;
using log4net;
using Medianet.Web.Helpers;
using Medianet.Web.MedianetCustomerService;
using Medianet.Web.MedianetGeneralService;
using Medianet.Web.MedianetReleaseService;
using Medianet.Web.Models;
using Medianet.Web.Validators;
using InvalidParameterFault = Medianet.Web.MedianetGeneralService.InvalidParameterFault;
using SystemType = Medianet.Web.MedianetCustomerService.SystemType;
using System.Net;

namespace Medianet.Web.Controllers
{
    public class TrainingCourseController : Controller
    {
        private const string Session_Training = "TRAINING";

        /// <summary>
        /// Step 1. Initial training course registration page.
        /// </summary>
        [HttpGet]
        public ActionResult Register(string courseId, int scheduleId, string promoCode)
        {
            TrainingCourseRegisterModel model;

            model = FetchCourseDetails(courseId, scheduleId, promoCode);

            return View("Register", model);
        }

        /// <summary>
        /// Step 2. Display both a creditcard payment page and an invoice option
        /// and allow the user to choose which way they want to pay.
        /// </summary>
        [HttpPost]
        public ActionResult Payment(TrainingCourseRegisterModel model)
        {
            return PaymentSteps(model);
        }

        /// <summary>
        /// Step 2. Redirect after creditcard payment failed.
        /// </summary>
        [HttpGet]
        public ActionResult Payment()
        {
            var model = (TrainingCourseRegisterModel)Session[Session_Training];

            if (model == null)
            {
                model = new TrainingCourseRegisterModel();
                LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType).Error("Payment could not find details in the session.");
                ModelState.AddModelError(string.Empty, "Details no longer available. Please return to the first step and start again.");
            }

            model.Prepare();
            return PaymentSteps(model);
        }

        [HttpGet]
        public ActionResult ApplyPromoCode(string courseId, int scheduleId, string promoCode)
        {
            var model = FetchCourseDetails(courseId, scheduleId, promoCode);

            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest, "Invalid model");
            }

            var code = model.PromoCodes.FirstOrDefault(c => c.PromoCode.Equals(promoCode, StringComparison.CurrentCultureIgnoreCase));

            if (code == null)
                return new HttpNotFoundResult("Invalid course");
            
            return Json(code, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Step 3. Callback method from eway after attempting to pay by creditcard.
        /// </summary>
        [HttpGet]
        public ActionResult Thanks(string debtorNumber, string AccessCode)
        {
            TrainingCourseRegisterModel model;

            if (string.IsNullOrWhiteSpace(debtorNumber) || string.IsNullOrWhiteSpace(AccessCode))
            {
                LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType).Error("TrainingCourse/Thanks called with missing parameters.");
                return View("~/Views/Home/500.cshtml", new ContactModel());
            }

            model = FinalisePayment(AccessCode, debtorNumber);

            if (!model.HasFinalised)
            {
                return RedirectToAction("Payment");
            }

            return View("Thanks", model);
        }

        ///// <summary>
        ///// Step 3. Method called when paying by invoice. Validate the ABN.
        ///// </summary>
        //[HttpPost]
        //public ActionResult Thanks(string abn)
        //{
        //    var model = (TrainingCourseRegisterModel)Session[Session_Training];
        //    string debtorNumber;

        //    if (model == null)
        //    {
        //        model = new TrainingCourseRegisterModel();
        //        model.PaymentMethod = TrainingCourseRegisterModel.PaymentMethod_Invoice;

        //        LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType).Error("Payment could not find details in the session.");
        //        ModelState.AddModelError(string.Empty, "Details no longer available. Please return to the first step and start again.");
        //        return View("Payment", model);
        //    }

        //    model.Prepare();
        //    model.ABN = abn;
        //    model.PaymentMethod = TrainingCourseRegisterModel.PaymentMethod_Invoice;

        //    var x = new ABNAttribute();
        //    if (!x.IsValid(model.ABN))
        //    {
        //        ModelState.AddModelError("ABN", "The field ABN must be a string with a maximum length of 11");
        //        return View("Payment", model);
        //    }
 
        //    // Update the customer ABN.
        //    debtorNumber = CreateOrUpdateCustomer(model);

        //    if (!ModelState.IsValid)
        //    {
        //        return View("Payment", model);
        //    }

        //    RegisterForCourse(model, debtorNumber, string.Empty, 0d);

        //    return View("Thanks", model);
        //}

        private void FetchCourseDetails(TrainingCourseRegisterModel model)
        {
            try
            {
                using (var svc = new ServiceProxyHelper<GeneralServiceClient, IGeneralService>())
                {
                    TrainingCourse course = svc.Proxy.GetTrainingCourse(model.CourseId);

                    if (course != null && course.EventType != EventType.Event)
                    {
                        model.CourseTitle = course.Title;
                        model.CourseSummary = course.Summary;
                        model.CourseDescription = course.Description;
                        model.CoursePrice = course.Price;
                        model.CourseTopics = new List<string>();
                        model.PromoCodes = new List<PromoCodeModel>();

                        if (course.PromoCodes != null)
                        {
                            foreach (var code in course.PromoCodes)
                            {
                                var x = new PromoCodeModel();
                                x.PromoCode = code.PromoCode;
                                x.PackageId = code.PackageId;
                                x.Price = code.Price;

                                model.PromoCodes.Add(x);
                            }
                        }

                        if (!string.IsNullOrWhiteSpace(model.PromoCode))
                        {
                            var code = model.PromoCodes.FirstOrDefault(
                                        c => c.PromoCode.Equals(model.PromoCode, StringComparison.CurrentCultureIgnoreCase));

                            if (code == null)
                            {
                                model.PromoCode = string.Empty;
                            }
                            else
                            {
                                model.CoursePrice = code.Price;
                            }
                        }

                        if (course.Topics != null)
                        {
                            foreach (var t in course.Topics)
                            {
                                model.CourseTopics.Add(t.Heading);
                            }
                        }

                        var sched = course.Schedules == null
                            ? null
                            : course.Schedules.FirstOrDefault(s => s.Id == model.ScheduleId);

                        if (sched != null)
                        {
                            var seatsTaken =
                                sched.Enrolments.Count(
                                    e => e.RowStatus == Medianet.Web.MedianetGeneralService.RowStatusType.Active);

                            model.ScheduleDate = sched.CourseDate;
                            model.ScheduleTime = sched.CourseTime;
                            model.ScheduleLocation = sched.LocationId;
                            model.ScheduleAddress = sched.Location.Description.Replace("\n", "<br />");
                            model.TotalSeats = sched.Seats;
                            model.SeatsRemaining = model.TotalSeats - seatsTaken;
                            model.ScheduleAgenda = sched.Agenda;
                            model.ScheduleFormHandler = sched.FormHandler;

                            if (sched.CourseDate < DateTime.Now)
                                ModelState.AddModelError(string.Empty,
                                    "This course is in the past and is no longer taking registrations.");

                            if (sched.Seats <= seatsTaken)
                                ModelState.AddModelError(string.Empty, "This course has reached maximum capacity. However you can check out other course dates, <a href='http://www.medianet.com.au/training_courses'>here</a>.");
                        }
                        else
                        {
                            ModelState.AddModelError(string.Empty, "The course schedule could not be found.");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "The course could not be found.");
                    }
                }
            }
            catch (Exception ex)
            {
                LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType).Error("FetchCourseDetails failed.", ex);

medianet-distribution-website/Medianet.Web/Views/TrainingCourse/Payment.cshtml
@using Medianet.Web.Models;
@using Medianet.Web.MedianetListService;
@model TrainingCourseRegisterModel
@{
    Layout = "~/Views/Shared/_LayoutAccount.cshtml";
}

<div class="row register">
    <div id="content" class="span8">
        <div class="intro">
            <h1>@Model.CourseTitle</h1>
            <br />
            <p>@Html.Raw(Model.CourseSummary)</p>
            @if (@Model.PaymentResponse == null)
            {
                <br />
                <h2>There was an error preparing the payment</h2>
            }
            <br />
        </div>

        <table class="panel">
            <thead class="panel-heading trainingCourse-heading">
                <tr>
                    <th style="width: 5%"></th>
                    <th style="width: 25%">Register</th>
                    <th style="width: 10%">
                        <img src="../../Content/img/chevron-right.png" />
                    </th>
                    <th style="width: 25%" class="active">Payment</th>
                    <th style="width: 10%">
                        <img src="../../Content/img/chevron-right.png" />
                    </th>
                    <th style="width: 20%">Confirmation</th>
                </tr>
            </thead>
        </table>

        <section class="panel trainingCourse">
            @Html.ValidationSummary(true)
            <div id="creditcard" class="payment">
                <div class="creditcards">
                    <h4>Medianet accepts the following credit cards:</h4>
                    <img src="@Url.Content("~/Content/img/creditcards.png")">
                </div>
                <div class="form-horizontal">
                    @if (@Model.PaymentResponse == null)
                    {
                        @Html.Raw(Model.Error)
                    }
                    else
                    {
                        <h4>Please enter your credit card details below. Your card will be charged @((Model.PaymentResponse.Total % 1 > 0) ? Model.PaymentResponse.Total.ToString("C") : Model.PaymentResponse.Total.ToString("C0")).</h4>
                        @Html.Raw(@Model.PaymentResponse.PaymentForm)
                    }
                </div>
                @if (!string.IsNullOrWhiteSpace(Model.PaymentError))
                {
                    <div class="intro payment-fail">
                        <h2>The credit card details are incorrect.</h2>
                        <p>Please try again. If you continue to experience an error, please contact our customer service team on 1300 616 813.</p>
                    </div>
                }
            </div>
            <div class="payment">
                <br/>
                <div class="buttons pull-left">
                    <input type="button" value="Back" onclick="location.href='@Url.Action("Register", "TrainingCourse", new RouteValueDictionary(new { courseId=Model.CourseId, scheduleId = Model.ScheduleId, promoCode = Model.PromoCode }))'"
                            class="btn btn-primary btn-tw btn-tw-green"/>
                </div>
                <br />
            </div>
        </section>
        @if (@Model.PaymentResponse != null)
        {
            @*<text>
            <div class="intro">
                <div id="ewayBlock">
                    <a href="https://www.eway.com.au/secure-site-seal" title="Credit Card Processing" target="_blank">Credit Card Processing</a>
                    <a href="https://www.eway.com.au/secure-site-seal" title="Payment Gateway" target="_blank">Payment Gateway</a>
                    <a href="https://www.eway.com.au/secure-site-seal" title="E-Commerce" target="_blank">E-Commerce</a>
                </div>
                <script language="javascript">
                    var element = "ewayBlock";
                </script>
                <script language="javascript" src="https://www.eway.com.au/developer/payment-code/verified-siteseal.ashx?image=10&amp;size=15&amp;format=horizontal&amp;color=CECECE"></script>
                ;
            </div>
            </text>*@
        }
    </div>

    <div id="sidebar" class="span4">
        <table class="panel table-condensed">
            <thead class="panel-heading">
            <tr>
                <th>Course Details</th>
            </tr>
            </thead>
            <tbody class="panel-body">
            <tr>
                <td>
                    <dl class="dl-horizontal">
                        <dt>Date:</dt>
                        <dd>@(Model.ScheduleDate.ToString("dddd ") + Model.ScheduleDate.Day.ToOrdinal() + Model.ScheduleDate.ToString(" MMMM, yyyy"))</dd>
                        <dt>Time:</dt>
                        <dd>@(Model.ScheduleTime)</dd>
                        <dt>Cost:</dt>
                        <dd>@((Model.CoursePrice % 1 > 0) ? Model.CoursePrice.ToString("C") : Model.CoursePrice.ToString("C0")) exc. GST <span id="promoCodeApplied" class="@(string.IsNullOrEmpty(Model.PromoCode) ? "hidden" : "")">(Promo code applied)</span></dd>
                    </dl>
                    <strong>Seats Remaining:</strong>&nbsp;@(Model.SeatsRemaining)
                </td>
            </tr>
            <tr>
                <td><strong>Location:</strong><br/>
                    @Html.Raw(Model.ScheduleAddress)
                </td>
            </tr>
            <tr>
                <td>
                    <strong>Telephone:</strong>&nbsp;02 9322 8140<br/>
                    <strong>Email:</strong>&nbsp;<a href="mailto:mediatraining@aap.com.au">mediatraining@aap.com.au</a>
                    <br/>
                    <br/>
                </td>
            </tr>
            </tbody>
        </table>

        @if (Model.CourseTopics != null && Model.CourseTopics.Count > 0)
        {
            <br />
            <br />

            <table class="panel">
                <thead class="panel-heading">
                    <tr>
                        <th>Outcomes</th>
                    </tr>
                </thead>
                <tbody class="panel-body">
                    @foreach (var t in Model.CourseTopics)
                    {
                        <tr>
                            <td><i class="fa fa-check"></i>@t</td>
                        </tr>
                    }
                </tbody>
            </table>
        }

        <br />
        <br />

        <p>Note: Costs cover facilitation, catering and workshop materials. Course
            will only proceed if minimum numbers are met.<br />
            Please read the <a href="https://www.medianet.com.au/media-training-terms-conditions/" target="_blank">terms and conditions</a> for more information.
        </p>
    </div>
</div>

<script src="@Url.Content("~/Scripts/medianet.course.payment.js")" type="text/javascript"></script>

medianet-distribution-website/Medianet.Web/Views/TrainingCourse/Thanks.cshtml
@using Medianet.Web.Models;
@using Medianet.Web.MedianetListService;
@model TrainingCourseRegisterModel
@{
    Layout = "~/Views/Shared/_LayoutAccount.cshtml";
}
<div class="row register">
    <div id="content" class="span8">
        <div class="intro">
            <h1>@Model.CourseTitle</h1>
            <br/>
            <p>@Html.Raw(Model.CourseSummary)</p>
            <br/>
        </div>

        <table class="panel">
            <thead class="panel-heading trainingCourse-heading">
            <tr>
                <th style="width: 5%"></th>
                <th style="width: 25%">Register</th>
                <th style="width: 10%">
                    <img src="../../Content/img/chevron-right.png"/>
                </th>
                <th style="width: 25%">Payment</th>
                <th style="width: 10%">
                    <img src="../../Content/img/chevron-right.png"/>
                </th>
                <th style="width: 20%" class="active">Confirmation</th>
            </tr>
            </thead>
        </table>

        <section class="panel trainingCourse">
            @if (string.IsNullOrWhiteSpace(Model.Error))
            {
                if (Model.PaymentMethod == TrainingCourseRegisterModel.PaymentMethod_Creditcard)
                {
                    <h4>Confirmed: Your registration has been successful</h4>
                    <br/>
                    <p>Shortly you will receive a confirmation email from us regarding
                        course information and what to bring with you on the day. You will be
                        required to respond with any dietary requirements for catering purposes.
                    </p>
                    <p>Please read the email and contact us if you have any questions.</p>
                    <p>We look forward to seeing you there!</p>
                    <p><a href="@Url.Action("Register", "TrainingCourse", new RouteValueDictionary(new { courseId=Model.CourseId, scheduleId = Model.ScheduleId }))">Click here to register another attendee</a></p>
                    <p><a href="https://www.medianet.com.au">Go to Medianet Home</a></p>
                }
                else
                {
                    <h4>Confirmed: Your registration has been successful</h4>
                    <br/>
                    <p>You will receive an email from our accounts department with your invoice to be paid.
                        Please ensure you have paid your invoice before the course.
                    </p>
                    <p>You will also receive a confirmation email regarding course information and what to bring with you on the day.
                        You will be required to respond with any dietary requirements for catering purposes.
                    </p>
                    <p>Should you have any information, please do not hesitate to contact us.</p>
                    <p>We look forward to seeing you there!</p>
                    <p><a href="@Url.Action("Register", "TrainingCourse", new RouteValueDictionary(new { courseId=Model.CourseId, scheduleId = Model.ScheduleId }))">Click here to register another attendee</a></p>
                    <p><a href="https://www.medianet.com.au">Go to Medianet Home</a></p>
                }
            }
            else
            {
                <h4>Something went wrong</h4>
                <p>Please try again. If you continue to experience an error, please contact our customer service team on 1300 616 813.</p>
            }
        </section>
    </div>

    <div id="sidebar" class="span4">
        <table class="panel table-condensed">
            <thead class="panel-heading">
            <tr>
                <th>Course Details</th>
            </tr>
            </thead>
            <tbody class="panel-body">
            <tr>
                <td>
                    <dl class="dl-horizontal">
                        <dt>Date:</dt>
                        <dd>@(Model.ScheduleDate.ToString("dddd ") + Model.ScheduleDate.Day.ToOrdinal() + Model.ScheduleDate.ToString(" MMMM, yyyy"))</dd>
                        <dt>Time:</dt>
                        <dd>@(Model.ScheduleTime)</dd>
                        <dt>Cost:</dt>
                        <dd>@((Model.CoursePrice % 1 > 0) ? Model.CoursePrice.ToString("C") : Model.CoursePrice.ToString("C0")) exc. GST <span id="promoCodeApplied" class="@(string.IsNullOrEmpty(Model.PromoCode) ? "hidden" : "")">(Promo code applied)</span></dd>
                    </dl>
                    <strong>Seats Remaining:</strong>&nbsp;@(Model.SeatsRemaining)
                </td>
            </tr>
            <tr>
                <td><strong>Location:</strong><br/>
                    @Html.Raw(Model.ScheduleAddress)
                </td>
            </tr>
            <tr>
                <td>
                    <strong>Telephone:</strong>&nbsp;02 9322 8140<br/>
                    <strong>Email:</strong>&nbsp;<a href="mailto:mediatraining@aap.com.au">mediatraining@aap.com.au</a>
                    <br/><br/>
                </td>
            </tr>
            </tbody>
        </table>

        @if (Model.CourseTopics != null && Model.CourseTopics.Count > 0)
        {
            <br />
            <br />

            <table class="panel">
                <thead class="panel-heading">
                    <tr>
                        <th>Outcomes</th>
                    </tr>
                </thead>
                <tbody class="panel-body">
                    @foreach (var t in Model.CourseTopics)
                    {
                        <tr>
                            <td><i class="fa fa-check"></i>@t</td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
</div>

<iframe src="@(Model.ScheduleFormHandler)?CourseName=@(HttpUtility.UrlEncode(Model.CourseTitle))&CourseDate=@(HttpUtility.UrlEncode(Model.ScheduleDate.ToString("yyyyMMdd")))&CourseLocation=@(HttpUtility.UrlEncode(Model.ScheduleLocation))&FirstName=@(HttpUtility.UrlEncode(Model.FirstName))&Lastname=@(HttpUtility.UrlEncode(Model.Lastname))&Company=@(HttpUtility.UrlEncode(Model.Company))&Position=@(HttpUtility.UrlEncode(Model.Position))&Email=@(HttpUtility.UrlEncode(Model.Email))&Phone=@(HttpUtility.UrlEncode(Model.Phone))" width="1" height="1"></iframe>

<script src="@Url.Content("~/Scripts/medianet.common.js")" type="text/javascript"></script>