medianet-distribution-website/Medianet.Web/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.ServiceModel;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using log4net;
using Medianet.Web.Helpers;
using Medianet.Web.MedianetCustomerService;
using Medianet.Web.MedianetGeneralService;
using Medianet.Web.MedianetReleaseService;
using Medianet.Web.Models;
using SystemType = Medianet.Web.MedianetCustomerService.SystemType;

namespace Medianet.Web.Controllers
{
    public class EventController : Controller
    {
        private const string Session_Event = "EVENT";

        /// <summary>
        /// Step 1. Initial Event registration page.
        /// </summary>
        [HttpGet]
        public ActionResult Register(string eventId, int scheduleId, string promoCode)
        {
            EventRegisterModel model;

            model = FetchEventDetails(eventId, scheduleId, promoCode);

            return View("Register", model);
        }

        [HttpPost]
        public PartialViewResult AddAttendee(List<EventAttendeeModel> attendees)
        {
            return PartialView("_attendeeRow", attendees);
        }

        [HttpGet]
        public ActionResult ApplyPromoCode(string eventId, int scheduleId, string promoCode)
        {
            var model = FetchEventDetails(eventId, scheduleId, promoCode);

            if (!ModelState.IsValid)
            {
                return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest, "Invalid model");
            }

            var code = model.PromoCodes.FirstOrDefault(
                                        c => c.PromoCode.Equals(promoCode, StringComparison.CurrentCultureIgnoreCase));

            if (code == null)
            {
                return new HttpNotFoundResult("Invalid event");
            }

            return Json(code, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Step 2. Display both a creditcard payment page and an invoice option
        /// and allow the user to choose which way they want to pay.
        /// </summary>
        [HttpPost]
        public ActionResult Payment(EventRegisterModel model)
        {
            return PaymentSteps(model);
        }

        /// <summary>
        /// Step 2. Redirect after creditcard payment failed.
        /// </summary>
        [HttpGet]
        public ActionResult Payment()
        {
            var model = (EventRegisterModel)Session[Session_Event];

            if (model == null)
            {
                model = new EventRegisterModel();
                LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType).Error("Payment could not find details in the session.");
                ModelState.AddModelError(string.Empty, "Details no longer available. Please return to the first step and start again.");
            }

            model.Prepare();
            return PaymentSteps(model);
        }

        /// <summary>
        /// Step 3. Callback method from eway after attempting to pay by creditcard.
        /// </summary>
        [HttpGet]
        public ActionResult Thanks(string debtorNumber, string AccessCode)
        {
            EventRegisterModel model;

            if (string.IsNullOrWhiteSpace(debtorNumber) || string.IsNullOrWhiteSpace(AccessCode))
            {
                LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType).Error("Event/Thanks called with missing parameters.");
                EmailHelper.SendErrorEmail("Event/Thanks called with missing parameters.");
                return View("~/Views/Home/500.cshtml", new ContactModel());
            }

            model = FinalisePayment(AccessCode, debtorNumber);

            if (!model.HasFinalised)
            {
                return RedirectToAction("Payment");
            }

            return View("Thanks", model);
        }

        [HttpGet]
        public ActionResult RegisterInterest(string eventId, int scheduleId, string promoCode)
        {
            EventRegisterModel model;

            model = FetchEventDetails(eventId, scheduleId, promoCode);

            return View("RegisterInterest", model);
        }

        private void FetchEventDetails(EventRegisterModel model)
        {
            try
            {
                using (var svc = new ServiceProxyHelper<GeneralServiceClient, IGeneralService>())
                {
                    TrainingCourse course = svc.Proxy.GetTrainingCourse(model.EventId);

                    if (course != null && course.EventType == EventType.Event)
                    {
                        model.EventTitle = course.Title;
                        model.EventSummary = course.Summary.Replace("\n", "<br />");
                        model.EventDescription = course.Description.Replace("\n", "<br />");
                        model.EventSector = course.Sector;
                        model.EventPrice = course.Price;
                        model.PromoCodes = new List<PromoCodeModel>();
                        model.Attendees = ParseAttendees(model.AttendeesString);

                        if (course.PromoCodes != null)
                        {
                            foreach (var code in course.PromoCodes)
                            {
                                var x = new PromoCodeModel();
                                x.PromoCode = code.PromoCode;
                                x.PackageId = code.PackageId;
                                x.Price = code.Price;

                                model.PromoCodes.Add(x);
                            }
                        }

                        if (!string.IsNullOrWhiteSpace(model.PromoCode))
                        {
                            var code = model.PromoCodes.FirstOrDefault(
                                        c => c.PromoCode.Equals(model.PromoCode, StringComparison.CurrentCultureIgnoreCase));

                            if (code == null)
                            {
                                model.PromoCode = string.Empty;
                            }
                            else
                            {
                                model.EventPrice = code.Price;
                            }
                        }

                        if (course.Contact != null)
                        {
                            model.ContactNumber = course.Contact.Number;
                            model.ContactEmail = course.Contact.Email;
                        }

                        var sched = course.Schedules == null
                            ? null
                            : course.Schedules.FirstOrDefault(s => s.Id == model.ScheduleId);

                        if (sched != null)
                        {
                            var seatsRequired = (model.Attendees != null && model.Attendees.Count > 1 ? model.Attendees.Count : 1);
                            var seatsTaken =
                                sched.Enrolments.Count(
                                    e => e.RowStatus == MedianetGeneralService.RowStatusType.Active);

                            model.ScheduleDate = sched.CourseDate;
                            model.ScheduleTime = sched.CourseTime;
                            model.ScheduleLocation = sched.LocationId;
                            model.ScheduleAddress = sched.Location.Description.Replace("\n", "<br />");
                            model.TotalSeats = sched.Seats;
                            model.SeatsRemaining = model.TotalSeats - seatsTaken;
                            model.ScheduleFormHandler = sched.FormHandler;

                            if (string.IsNullOrWhiteSpace(sched.Agenda))
                                model.ScheduleAgenda = new List<string>();
                            else
                                model.ScheduleAgenda = sched.Agenda.Split(new string[] { "\n" }, StringSplitOptions.RemoveEmptyEntries).ToList();

                            if (sched.CourseDate < DateTime.Now)
                                ModelState.AddModelError(string.Empty,
                                    "This event is in the past and is no longer taking registrations.");

                            if (model.SeatsRemaining < seatsRequired)
                                ModelState.AddModelError(string.Empty, string.Format("This event has reached maximum capacity. However you can register your interest for future events <a href='/Event/RegisterInterest?eventId={0}&scheduleId={1}'>here</a>.", model.EventId, model.ScheduleId));
                        }
                        else
                        {
                            ModelState.AddModelError(string.Empty, "The event schedule could not be found.");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "The event could not be found.");
                    }
                }
            }
            catch (Exception ex)
            {
                LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType).Error("GetTrainingCourse failed.", ex);
                ModelState.AddModelError(string.Empty, "Error fetching event details.");
            }
        }

        private EventRegisterModel FetchEventDetails(string eventId, int scheduleId, string promoCode)
        {
            var model = (EventRegisterModel)Session[Session_Event];

            if (model == null || (model.EventId != eventId && model.ScheduleId != scheduleId))
            {
                model = new EventRegisterModel();
                model.EventId = eventId;
                model.ScheduleId = scheduleId;
            }
            else
            {
                model.Prepare();
            }

            if (!string.IsNullOrWhiteSpace(promoCode))
                model.PromoCode = promoCode;

medianet-distribution-website/Medianet.Web/Views/Event/Payment.cshtml
@using Medianet.Web.Models;
@using Medianet.Web.MedianetListService;
@model EventRegisterModel
@{
    Layout = "~/Views/Shared/_LayoutAccount.cshtml";
}

<div class="row register">
    <div id="content" class="span8">
        <div class="intro">
            <h1>@Model.EventTitle</h1>
            <br />
            <p>@Html.Raw(Model.EventSummary)</p>
            @if (@Model.PaymentResponse == null)
            {
                <br />
                <h2>There was an error preparing the payment</h2>
            }
            <br />
        </div>

        <table class="panel">
            <thead class="panel-heading trainingCourse-heading">
                <tr>
                    <th style="width: 5%"></th>
                    <th style="width: 25%">Register</th>
                    <th style="width: 10%">
                        <img src="../../Content/img/chevron-right.png" />
                    </th>
                    <th style="width: 25%" class="active">Payment</th>
                    <th style="width: 10%">
                        <img src="../../Content/img/chevron-right.png" />
                    </th>
                    <th style="width: 20%">Confirmation</th>
                </tr>
            </thead>
        </table>

        <section class="panel trainingCourse">
            @Html.ValidationSummary(true)
            <div id="creditcard" class="payment">
                <div class="creditcards">
                    <h4>Medianet accepts the following credit cards:</h4>
                    <img src="@Url.Content("~/Content/img/creditcards.png")">
                </div>
                <div class="form-horizontal">
                    @if (@Model.PaymentResponse == null)
                    {
                        @Html.Raw(Model.Error)
                    }
                    else
                    {
                        <div style="text-align: center;"><h4>Please enter your credit card details below. Your card will be charged @((Model.PaymentResponse.Total % 1 > 0) ? Model.PaymentResponse.Total.ToString("C") : Model.PaymentResponse.Total.ToString("C0")) inc. GST for @(Model.Attendees.Count.ToString()) tickets.</h4></div>
                        <br/>
                        <br/>
                        @Html.Raw(@Model.PaymentResponse.PaymentForm)
                    }
                </div>
                @if (!string.IsNullOrWhiteSpace(Model.PaymentError))
                {
                    <div class="intro payment-fail">
                        <h2>The credit card details are incorrect.</h2>
                        <p>Please try again. If you continue to experience an error, please contact our customer service team on 1300 616 813.</p>
                    </div>
                }
            </div>
            <div class="payment">
                <br/>
                <div class="buttons pull-left">
                    <input type="button" value="Back" onclick="location.href='@Url.Action("Register", "Event", new RouteValueDictionary(new { eventId=Model.EventId, scheduleId = Model.ScheduleId, promoCode = Model.PromoCode }))'" class="btn btn-primary btn-tw btn-tw-green"/>
                </div>
                <br />
            </div>
        </section>
        @if (@Model.PaymentResponse != null)
        {
            @*<text>
            <div class="intro">
                <div id="ewayBlock">
                    <a href="https://www.eway.com.au/secure-site-seal" title="Credit Card Processing" target="_blank">Credit Card Processing</a>
                    <a href="https://www.eway.com.au/secure-site-seal" title="Payment Gateway" target="_blank">Payment Gateway</a>
                    <a href="https://www.eway.com.au/secure-site-seal" title="E-Commerce" target="_blank">E-Commerce</a>
                </div>
                <script language="javascript">
                    var element = "ewayBlock";
                </script>
                <script language="javascript" src="https://www.eway.com.au/developer/payment-code/verified-siteseal.ashx?image=10&amp;size=15&amp;format=horizontal&amp;color=CECECE"></script>
                ;
            </div>
            </text>*@
        }
    </div>

    <div id="sidebar" class="span4">
        <table class="panel table-condensed">
            <thead class="panel-heading">
            <tr>
                <th>Event Details</th>
            </tr>
            </thead>
            <tbody class="panel-body">
            <tr>
                <td>
                    <dl class="dl-horizontal">
                        <dt>Date:</dt>
                        <dd>@(Model.ScheduleDate.ToString("dddd ") + Model.ScheduleDate.Day.ToOrdinal() + Model.ScheduleDate.ToString(" MMMM, yyyy"))</dd>
                        <dt>Time:</dt>
                        <dd>@(Model.ScheduleTime)</dd>
                        <dt>Cost:</dt>
                        <dd>@((Model.EventPrice % 1 > 0) ? Model.EventPrice.ToString("C") : Model.EventPrice.ToString("C0")) exc. GST (per ticket)</dd>
                        <dt>Sector:</dt>
                        <dd>@(Model.EventSector)</dd>
                    </dl>
                </td>
            </tr>
            <tr>
                <td><strong>Location:</strong><br/>
                    @Html.Raw(Model.ScheduleAddress)
                </td>
            </tr>
            <tr>
                <td>
                    <strong>Telephone:</strong>&nbsp;@(Model.ContactNumber == null ? "" : Model.ContactNumber)<br/>
                    @if (!string.IsNullOrWhiteSpace(Model.ContactEmail))
                    {
                        @:<strong>Email:</strong>&nbsp;<a href="mailto:@(Model.ContactEmail)">@(Model.ContactEmail)</a>
                    }
                    <br/>
                    <br/>
                </td>
            </tr>
            </tbody>
        </table>

        @if (Model.ScheduleAgenda != null && Model.ScheduleAgenda.Count > 0)
        {
            <br />
            <br />

            <table class="panel">
                <thead class="panel-heading">
                    <tr>
                        <th>Panellists</th>
                    </tr>
                </thead>
                <tbody class="panel-body">
                    @foreach (var t in Model.ScheduleAgenda)
                    {
                        <tr>
                            <td><i class="fa fa-circle"></i>&nbsp;@t</td>
                        </tr>
                    }
                </tbody>
            </table>
        }

        <br />
        <br />

        <p>Note: Costs cover facilitation, catering and workshop materials. Event
            will only proceed if minimum numbers are met.<br />
            Please read the <a href="https://www.medianet.com.au/aap-masterclass-terms-conditions/" target="_blank">terms and conditions</a> for more information.
        </p>
    </div>
</div>

<script src="@Url.Content("~/Scripts/medianet.course.payment.js")" type="text/javascript"></script>

medianet-distribution-website/Medianet.Web/Views/Event/Register.cshtml
@model Medianet.Web.Models.EventRegisterModel
@{
    ViewBag.Title = "Register for Event";
    Layout = "~/Views/Shared/_LayoutAccount.cshtml";
    Html.EnableClientValidation();
}

<div class="row register">
<div id="content" class="span8">
<div class="intro">
    <h1>@Model.EventTitle</h1>
    <br/>
    <p>@Html.Raw(Model.EventSummary)</p>
    <br/>
</div>
<table class="panel">
    <thead class="panel-heading trainingCourse-heading">
    <tr>
        <th style="width: 5%"></th>
        <th style="width: 25%" class="active">Register</th>
        <th style="width: 10%">
            <img src="../../Content/img/chevron-right.png"/>
        </th>
        <th style="width: 25%">Payment</th>
        <th style="width: 10%">
            <img src="../../Content/img/chevron-right.png"/>
        </th>
        <th style="width: 20%">Confirmation</th>
    </tr>
    </thead>
</table>

<section>
    @using (Html.BeginForm("Payment", "Event", FormMethod.Post, new {@class = "panel trainingCourse"}))
    {
        @Html.AntiForgeryToken()
        <!--Html.ValidationSummary(true)-->
        @Html.HiddenFor(m => m.EventId)
        @Html.HiddenFor(m => m.ScheduleId)
        @Html.HiddenFor(m => m.AttendeesString)
        @Html.HiddenFor(m => m.PromoCode)

        if (ViewData.ModelState.Any(v => string.IsNullOrWhiteSpace(v.Key) && v.Value.Errors.Count > 0))
        {
            <div class="validation-summary-errors">
                <ul>
                    @foreach (var modelState in ViewData.ModelState.Where(v => string.IsNullOrWhiteSpace(v.Key)))
                    {
                        ModelState modelStateValue = modelState.Value;
                        foreach (ModelError error in modelStateValue.Errors)
                        {
                            <li>@Html.Raw(error.ErrorMessage)</li>
                        }
                    }
                </ul>
            </div>
        }
        else
        {
            <h3>Attendees</h3>
            <br/>
            <table class="table" id="attendeeGrid" style="border: 1px solid #ccc;">
                <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Position</th>
                    <th>Company</th>
                    <th>&nbsp;</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="3"><div id="promoCodeApplied" class="hidden"><i class="fa fa-check"></i>Promo code applied</div></td>
                    <td colspan="3"><div class="pull-right strong">Total Price exc. GST</div></td>
                    <td style="padding-top: 10px;"><div id="totalPrice" class="pull-right strong">$0</div></td>
                </tr>
                </tfoot>
            </table>
            <div class="row">
                <div class="buttons pull-right">
                    <input type="button" id="addAttendee" value="Add Attendee" class="btn btn-small btn-tw btn-tw-default"/>
                </div>
            </div>
            <br/>
            <h3>Billing Information</h3>
            <br/>
            <div class="row">
                <div class="control-group span3">
                    <label class="control-label" for="FirstName">
                        First name
                        <abbr title="required">*</abbr></label>
                    <div class="controls">
                        @Html.TextBoxFor(m => m.FirstName, new { maxlength = 50 })
                        @Html.ValidationMessageFor(m => m.FirstName)
                    </div>
                </div>
                <div class="control-group span3 offset1">
                    <label class="control-label" for="LastName">
                        Last name
                        <abbr title="required">*</abbr></label>
                    <div class="controls">
                        @Html.TextBoxFor(m => m.Lastname, new { maxlength = 50 })
                        @Html.ValidationMessageFor(m => m.Lastname)
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="control-group span3">
                    <label class="control-label" for="Company">
                        Company
                        <abbr title="required">*</abbr></label>
                    <div class="controls">
                        @Html.TextBoxFor(m => m.Company, new { maxlength = 50 })
                        @Html.ValidationMessageFor(m => m.Company)
                    </div>
                </div>
                <div class="control-group span3 offset1">
                    <label class="control-label" for="Email">
                        Email Address
                        <abbr title="required">*</abbr></label>
                    <div class="controls">
                        @Html.TextBoxFor(m => m.Email, new { maxlength = 50 })
                        @Html.ValidationMessageFor(m => m.Email)
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="control-group span3">
                    <label class="control-label" for="Address">
                        Address
                        <abbr title="required">*</abbr></label>
                    <div class="controls">
                        @Html.TextBoxFor(m => m.Address, new {maxlength = 50})
                        @Html.ValidationMessageFor(m => m.Address)
                    </div>
                </div>
                <div class="control-group span3 offset1">
                    <label class="control-label" for="Suburb">
                        Suburb
                        <abbr title="required">*</abbr></label>
                    <div class="controls">
                        @Html.TextBoxFor(m => m.Suburb, new {maxlength = 30})
                        @Html.ValidationMessageFor(m => m.Suburb)
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="control-group span3">
                    <label class="control-label" for="PostCode">
                        Postcode
                        <abbr title="required">*</abbr></label>
                    <div class="controls">
                        @Html.TextBoxFor(m => m.PostCode, new {maxlength = 10})
                        @Html.ValidationMessageFor(m => m.PostCode)
                    </div>
                </div>
                <div class="control-group span3 offset1">
                    <label class="control-label" for="State">
                        State
                        <abbr title="required">*</abbr></label>
                    <div class="controls">
                        @Html.DropDownListFor(m => m.State, Model.States)
                        @Html.ValidationMessageFor(m => m.State)
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="control-group span3">
                    <label class="control-label" for="Country">
                        Country
                        <abbr title="required">*</abbr>
                    </label>
                    <div class="controls">
                        @Html.DropDownListFor(m => m.Country, Model.Countries)
                        @Html.ValidationMessageFor(m => m.Country)
                    </div>
                </div>
                <div class="control-group span3 offset1">
                    <label class="control-label" for="Phone">
                        Contact number
                        <abbr title="required">*</abbr></label>
                    <div class="controls">
                        @Html.TextBoxFor(m => m.Phone, new { maxlength = 20 })
                        @Html.ValidationMessageFor(m => m.Phone)
                    </div>
                </div>
            </div>
            <div class="row">
                <br/>
                <div class="control-group span4 pull-left">
                    <div>
                        <label class="control-label">
                            @Html.CheckBoxFor(m => m.AgreeConditions)
                            I agree to the Terms of <a href="#terms" role="button" data-toggle="modal">Medianet</a> and <a href="https://www.medianet.com.au/aap-masterclass-terms-conditions/" target="_blank">attending this event</a>
                        </label>
                        @Html.ValidationMessageFor(m => m.AgreeConditions)
                    </div>
                    <div>
                        <label class="control-label">
                            <a href="https://www.medianet.com.au/privacy-policy/" target="_blank">Medianet Privacy Policy</a>
                        </label>
                    </div>
                    <div class="modal hide" id="terms" tabindex="-1" role="dialog" aria-labelledby="terms" aria-hidden="true">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true" onclick="$('#terms').hide();">×</button>
                            <h3 id="myModalLabel">Terms and Conditions</h3>
                        </div>
                        <div class="modal-body">
                            @Html.Partial("_terms")
                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-primary btn-tw btn-tw-green" data-dismiss="modal" aria-hidden="true" onclick="$('#terms').hide();">Close</button>
                        </div>
                    </div>
                </div>

                <div class="buttons pull-right">
                    <input type="submit" id="submitStep1" value="Next" class="btn btn-primary btn-tw btn-tw-green"/>
                </div>
                <br/>
            </div>
        }
    }
</section>
</div>

<div id="sidebar" class="span4">
    <table class="panel table-condensed">
        <thead class="panel-heading">
        <tr>
            <th>Event Details</th>
        </tr>
        </thead>
        <tbody class="panel-body">
        <tr>
            <td>
                <dl class="dl-horizontal">
                    <dt>Date:</dt>
                    <dd>@(Model.ScheduleDate.ToString("dddd ") + Model.ScheduleDate.Day.ToOrdinal() + Model.ScheduleDate.ToString(" MMMM, yyyy"))</dd>
                    <dt>Time:</dt>
                    <dd>@(Model.ScheduleTime)</dd>
                    <dt>Cost:</dt>
                    <dd><span id="price" data-price="@(Model.EventPrice)">@((Model.EventPrice % 1 > 0) ? Model.EventPrice.ToString("C") : Model.EventPrice.ToString("C0"))</span> exc. GST (per ticket)</dd>
                    <dt>Sector:</dt>
                    <dd>@(Model.EventSector)</dd>
                </dl>
            </td>
        </tr>
        <tr>
            <td><strong>Location:</strong><br/>
                @Html.Raw(Model.ScheduleAddress)
            </td>
        </tr>
        <tr>
            <td>
                <strong>Telephone:</strong>&nbsp;@(Model.ContactNumber == null ? "" : Model.ContactNumber)<br/>
                @if (!string.IsNullOrWhiteSpace(Model.ContactEmail))
                {
                    @:<strong>Email:</strong>&nbsp;<a href="mailto:@(Model.ContactEmail)">@(Model.ContactEmail)</a>
                }
                <br/>
                <br/>
            </td>
        </tr>
        </tbody>
    </table>

    <br/>
    <br/>

    <table class="panel">
        <thead class="panel-heading">
        <tr>
            <th>Promo Code</th>
        </tr>
        </thead>
        <tbody class="panel-body">
        <tr>
            <td>
                <label class="control-label" for="PromoCode">Enter Promo code</label>
                <input id="promoCodeToApply" maxlength="20" name="promoCodeToApply" type="text" value="">
                <input id="applyPromoCode" type="button" value="Apply" class="btn btn-small btn-tw btn-tw-default" style="margin-bottom: 9px;" />
            </td>
        </tr>
        </tbody>
    </table>

    @if (Model.ScheduleAgenda != null && Model.ScheduleAgenda.Count > 0)
    {
        <br />
        <br />

        <table class="panel">
            <thead class="panel-heading">
                <tr>
                    <th>Panellists</th>
                </tr>
            </thead>
            <tbody class="panel-body">
                @foreach (var t in Model.ScheduleAgenda)
                {
                    <tr>
                        <td><i class="fa fa-circle"></i>&nbsp;@t</td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>
</div>

@Html.Partial("_addAttendeePopup")

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/medianet.common.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/medianet.course.js")" type="text/javascript"></script>

medianet-distribution-website/Medianet.Web/Views/Event/_attendeeRow.cshtml
@using Medianet.Web.Models;
@model List<EventAttendeeModel>
@{
    ViewBag.Title = "Person";
}
@if (Model != null)
{
    foreach (var attendee in Model)
    {
        <tr style="background-color: #f9f9f9;">
            <td data-for="firstName">@attendee.FirstName</td>
            <td data-for="lastName">@attendee.Lastname</td>
            <td data-for="emailAddress">@attendee.Email</td>
            <td data-for="phoneNumber">@attendee.Phone</td>
            <td data-for="position">@attendee.Position</td>
            <td data-for="companyName">@attendee.Company</td>
            <td><input type="button" value="Remove" class="btn btn-small btn-tw btn-tw-default" onclick="removeAttendee(this);"/></td>
        </tr>
    }
}